### ISSUE TITLE
Can the tool keep the position of current selected line when we turn on/off "Show all logs temporarily"?

### ISSUE THREAD

**Issue by elmarlee** [carina-studio/ULogViewer#24]
Thanks for the handy tool, it helped me a lot!
I have a question, I don't find an easy way to find the line on interests when I toggle "Show all logs temporarily" option.

**Comment by hamster620** [comment]
Hi @elmarlee , ULogViewer will try keeping the viewport after toggling ```Show all logs temporarily```, but it may not be accurate because the set of logs to be displayed has been changed. I suggest that you can mark the log you interest (by pressing ```M``` or right-click on log) before toggling ```Show all logs temporarily```, then you can find it easily in ```Marked logs``` panel at right hand side of window.

**Comment by elmarlee** [comment]
Thanks for your suggestions!
