### ISSUE TITLE
Parsing JSON files from NLog

### ISSUE THREAD

**Issue by ZeroAviation** [carina-studio/ULogViewer#25]
Hi, 

I want to parse JSON files from an application which uses nlog. I can specify the layout in any manner. 

The question is, is using "Log line patterns" and regex the only option? or can I directly access the json schema? 

Thanks in advance!

**Comment by ZeroAviation** [comment]
Here is an example file

[example.json](https://github.com/carina-studio/ULogViewer/files/13480009/example.json)

**Comment by hamster620** [comment]
@ZeroAviation Yes, currently using ```Log line patterns``` is the only way to parse raw logs including JSON files.

If the file contains **valid** JSON format data, you can let ULogViewer format the raw JSON data by enabling ```Format JSON data when reading```:
<img width="612" alt="截圖 2023-11-28 清晨7 59 31" src="https://github.com/carina-studio/ULogViewer/assets/26860570/a0858b74-b456-4086-8829-ae2eff5020a2">

Then you will get formatted JSON data:
<img width="1464" alt="截圖 2023-11-28 上午8 02 12" src="https://github.com/carina-studio/ULogViewer/assets/26860570/b4864238-6a7b-45a2-930b-fdbfaf3be2c6">

Because JSON properties will be separated into multiple lines, it is easier to define ```Log line patterns``` with multiple patterns which is more flexible to add/remove patterns in the future. You can also set ```Way of matching log lines with patterns``` to ```Arbitrary order``` to ignore the order of JSON properties:
<img width="712" alt="截圖 2023-11-28 上午8 05 05" src="https://github.com/carina-studio/ULogViewer/assets/26860570/d70e665e-1d14-40ef-a25d-31824ff6fdd7">

But in your case the JSON file contains **incomplete** JSON data, ULogViewer cannot parse it correctly. We will try adding ability to parse incomplete JSON data in the next version.

**Comment by hamster620** [comment]
Now JSON data with multiple root elements can be formatted in [4.0.1.1222](https://github.com/carina-studio/ULogViewer/releases/tag/4.0.1.1222).
